version: '3'

services:
  docker-mysql:
    image: mysql:8
    container_name: docker-mysql
    ports:
       - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=full-stack-ecommerce
       - MYSQL_USER=ecommerceapp
       - MYSQL_PASSWORD=ecommerceapp
    restart: always
      
  backend:
    image: gunerhanale/ecommerce-backend
    container_name: ecommerce-backend
    ports:
       - "8080:8080"
    depends_on:
       - docker-mysql
    restart: always
    links:
      - docker-mysql
  
  frontend:
    image: gunerhanale/ecommerce-frontend
    container_name: ecommerce-frontend
    depends_on:
       - backend
    restart: always
    ports:
       - "4200:80" 
    links:
      - backend