version: '3'

services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=ecommerce
           - MYSQL_DATABASE=ecommerce
           - MYSQL_USER=ecommerce
           - MYSQL_PASSWORD=ecommerce
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    build: ./backend/spring-boot-ecommerce/
    ports:
           - "8080"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    build: ./frontend/angular-ecommerce/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "4200:4200" 